version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8081:80
    depends_on:
      - app
    container_name: landing_nginx

  app:
    build:
      args:
        user: ubuntu
        uid: 1000
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./src:/var/www
    container_name: landing_app
